// this code was autogenerated from PJS
(function($p) {

    var font = null;
    var input = "Microbot";
    var angle = 0;

    function setup() {
        $p.size(1280, 720);
        $p.textAlign($p.CENTER, $p.CENTER);
        font = $p.createFont("Helvetica", 60);
        $p.textFont(font);
        $p.noStroke();
    }
    $p.setup = setup;
    setup = setup.bind($p);

    function draw() {
        $p.fill(255, 5);
        $p.rect(0, 0, $p.width, $p.height);

        $p.fill(60);
        $p.textSize($p.mouseX + 4);

        $p.translate($p.width / 2, $p.mouseY);
        $p.rotate($p.radians(angle));

        $p.text(input, 0, 0);

        angle += 1;
    }
    $p.draw = draw;
    draw = draw.bind($p);

    function mousePressed() {
        $p.fill($p.random(255));
    }
    $p.mousePressed = mousePressed;
    mousePressed = mousePressed.bind($p);

    function keyPressed() {
        if ($p.key == $p.BACKSPACE) {
            var lastLetter = input.length - 1;
            if (lastLetter < 0) lastLetter = 0;
            input = input.substring(0, lastLetter);
        } else if ($p.key != $p.CODED) {
            input += $p.key;
        }
    }
    $p.keyPressed = keyPressed;
    keyPressed = keyPressed.bind($p);
})
