// this code was autogenerated from PJS
var sketchProc = function($p) {

    var theta = 0,
        diam = 0;
    var letras = null;
    var font = null;
    var paso = 24;

    function setup() {
        $p.background(0);
        $p.size(800, 500);
        $p.noStroke();
        $p.fill(8, 25, 92);

        letras = $p.createGraphics($p.width, $p.height);

        font = $p.createFont("WeAreAlien", 32);

        Stuff();
    }
    $p.setup = setup;
    setup = setup.bind($p);

    function draw() {
        $p.background(0);

        for (var x = paso / 2; x < $p.width; x += paso) {
            for (var y = paso / 2; y < $p.height; y += paso) {
                var c = letras.pixels.getPixel(x + y * $p.width);
                if ($p.brightness(c) > 50) {
                    diam = paso * .5;
                } else {
                    diam = $p.map($p.sin(theta), -1, 1, paso * .2, paso * .9);
                }

                $p.ellipse(x, y, diam, diam);
            }
        }

        theta += .05273;
    }
    $p.draw = draw;
    draw = draw.bind($p);

    function Stuff() {
        letras.beginDraw();
        letras.noStroke();
        letras.background(0, 0, 255);
        letras.fill(0);
        letras.textFont(font, 500);
        letras.textAlign($p.CENTER, $p.CENTER);
        letras.text("25", $p.width / 2, $p.height / 2);
        letras.endDraw();
        letras.loadPixels();
    }
    $p.Stuff = Stuff;
    Stuff = Stuff.bind($p);

};

var canvas = document.getElementById("mysketch");
//attaching the sketchProc function to the canvas
var p = new Processing(canvas, sketchProc);
